networks:
  upb-rental:
    external: false

services:
  upb-rental-web:
    build:
      dockerfile: web.Dockerfile
    image: upb-rental-web
    container_name: upb-rental-web
    restart: unless-stopped
    user: 5000:5000
    networks:
      - upb-rental
    environment:
      - DB_HOST=upb-rental-database:3306
      - DB_SCHEMA=upb_rental
      - DB_USER=upb_rental
      - DB_PASSWORD=upb_rental
    volumes:
      - ./src:/opt/upb-rental
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - upb-rental-database
  upb-rental-database:
    image: mariadb:latest
    container_name: upb-rental-database
    restart: unless-stopped
    networks:
      - upb-rental
    environment:
      - MYSQL_ROOT_PASSWORD=upb_rental
      - MYSQL_USER=upb_rental
      - MYSQL_PASSWORD=upb_rental
      - MYSQL_DATABASE=upb_rental
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - ./mysql:/var/lib/mysql